--- 
- 
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: true
  hosts: sonar
  remote_user: centos
  roles: 
    - geerlingguy.java
    - ansible-role-sonarqube
  vars: 
    java_packages: 
      - java-1.8.0-openjdk
