apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: staging
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: sunehagoel/webapp:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
